version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: ez_tro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tevc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tevc_net

  backend:
    image: ${DOCKER_USERNAME}/ez_tro_api:${BACKEND_IMAGE_TAG}
    container_name: ez_tro_backend
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tevc_net

  nginx:
    image: ${DOCKER_USERNAME}/ez_tro_app:${FRONTEND_IMAGE_TAG}
    container_name: ez_tro_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - tevc_cms_uploads:/uploads:ro
    depends_on:
      - backend
    networks:
      - tevc_net

volumes:
  mysql_data:
  tevc_cms_uploads:

networks:
  tevc_net:
    driver: bridge
