name: ci

on:
  pull_request:
    branches:
#      - main
      - staging


permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend:
    name: Build backend
    uses: ./.github/workflows/build-backend-image.yml
    with:
      image_name: ez-tro-backend
      image_tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
      push: false

  frontend:
    name: Build and test frontend
    uses: ./.github/workflows/build-frontend-image.yml
    with:
      image_name: ez-tro-frontend
      image_tag: pr-${{ github.event.pull_request.number }}-${{ github.sha }}
      react_app_api_url: /api
      react_app_ws_url: ws://localhost/ws
      react_app_minio_url: http://your-domain.com/minio
      push: false
